// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLNICJNNqX6r3HpFtkYaHfrWmhEJ4Gu3c',
    appId: '1:673282327541:web:b521775f4e736f331f96bc',
    messagingSenderId: '673282327541',
    projectId: 'preva-app',
    authDomain: 'preva-app.firebaseapp.com',
    storageBucket: 'preva-app.firebasestorage.app',
    measurementId: 'G-XN845C3464',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPOc2PECV5QDN6tZHjudWjbpzSnVTQ9Ds',
    appId: '1:673282327541:android:a300a37f309fba371f96bc',
    messagingSenderId: '673282327541',
    projectId: 'preva-app',
    storageBucket: 'preva-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLNICJNNqX6r3HpFtkYaHfrWmhEJ4Gu3c',
    appId: '1:673282327541:web:b73de60d856610cf1f96bc',
    messagingSenderId: '673282327541',
    projectId: 'preva-app',
    authDomain: 'preva-app.firebaseapp.com',
    storageBucket: 'preva-app.firebasestorage.app',
    measurementId: 'G-YN638TMXC1',
  );
}
